version: '3.4'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=root
  spring:
    image: accessing-data-mysql:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: always

